name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - run: make deps
    - run: make all
    
    - id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    
#    - run: tar -czvf gotrue-x86.${{ steps.vars.outputs.sha_short }}.tar.gz gotrue migrations/
#    - run: mv gotrue-arm64 gotrue
#    - run: tar -czvf gotrue-arm64.${{ steps.vars.outputs.sha_short }}.tar.gz gotrue migrations/
    
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          SOURCE: "gotrue, migrations"
          TARGET: ${{ secrets.DEPLOY_PATH }}
  
